apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deployment
  labels:
    app: customers-deployment
spec:
  selector:
    matchLabels:
      app: customers-deployment
  template:
    metadata:
      labels:
        app: customers-deployment
    spec:
      containers:
        - name: customers
          image: docker.io/bazel/pkgs/customers:image
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: crdb-service
            - name: DATABASE_PORT
              value: "26250"
            - name: DATABASE_USER
              value: root
            - name: DATABASE_PASSWORD
              value: ""