apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-web
  labels:
    app: temporal-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-web
  template:
    metadata:
      labels:
        app: temporal-web
    spec:
      containers:
        - name: temporal-web
          image: temporalio/web:latest
          ports:
            - containerPort: 8083