GRPC localhost:8081/CustomerService/CreateCustomer

{
  "email": "potatoGirl@gmail.com",
  "first_name": "test",
  "last_name": "test_last",
  "address": "tweeq"
}

###
GRPC localhost:8081/CustomerService/GetCustomerByEmail

{
  "email": "potato@gmail.com"
}

###
GRPC localhost:8081/CustomerService/GetTopCustomers

{

}
