apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-deployment
  labels:
    app: transactions-deployment
spec:
  selector:
    matchLabels:
      app: transactions-deployment
  template:
    metadata:
      labels:
        app: transactions-deployment
    spec:
      containers:
        - name: transactions
          image: bazel/pkgs/transactions/server:image
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: crdb-service
            - name: DATABASE_PORT
              value: "26250"
            - name: DATABASE_USER
              value: root
            - name: DATABASE_PASSWORD
              value: ""