apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: products-deployment
spec:
  selector:
    matchLabels:
      app: products-deployment
  template:
    metadata:
      labels:
        app: products-deployment
    spec:
      containers:
        - name: products
          image: bazel/pkgs/products/server:image
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: crdb-service
            - name: DATABASE_PORT
              value: "26250"
            - name: DATABASE_USER
              value: root
            - name: DATABASE_PASSWORD
              value: ""