GRPC localhost:8082/ProductService/CreateProduct

{
  "title": "potato",
  "price": 20.0,
  "qty": 200
}

###
GRPC localhost:8081/CustomerService/GetCustomerByEmail

{
  "email": "potatoGirl@gmail.com"
}

###
GRPC localhost:8081/CustomerService/GetTopCustomers

{

}
